In [69]:
%config IPCompleter.greedy=True

In [70]:
import numpy as np

In [71]:
##load data

filename = 'breast-cancer-wisconsin.data'

data = np.loadtxt(filename, delimiter=',')
data


array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

In [72]:
#replaces the outcome in each vector
def replace(vector,index):
    if vector[index]==4:
        vector[index]=1
        return vector
    else:
        vector[index]=0
        return vector
    
# replace(data[0],10)

In [73]:
def preproc(dataset):
    for element in dataset:
        element=replace(element,10)
    temp= dataset
    temp=np.insert(temp, 1, 1, axis=1)
    return temp    

data = preproc(data)
print(data)
data[:,11]

[[1.000025e+06 1.000000e+00 5.000000e+00 ... 1.000000e+00 1.000000e+00
  0.000000e+00]
 [1.002945e+06 1.000000e+00 5.000000e+00 ... 2.000000e+00 1.000000e+00
  0.000000e+00]
 [1.015425e+06 1.000000e+00 3.000000e+00 ... 1.000000e+00 1.000000e+00
  0.000000e+00]
 ...
 [8.888200e+05 1.000000e+00 5.000000e+00 ... 1.000000e+01 2.000000e+00
  1.000000e+00]
 [8.974710e+05 1.000000e+00 4.000000e+00 ... 6.000000e+00 1.000000e+00
  1.000000e+00]
 [8.974710e+05 1.000000e+00 4.000000e+00 ... 4.000000e+00 1.000000e+00
  1.000000e+00]]


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1.

In [74]:
data.shape

(683, 12)

In [75]:
#sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

    

In [76]:
sigmoid(0.3)

0.574442516811659

In [77]:
#not actually needed

def logodds(index,value,dataset):
    featureX = dataset[dataset[:,index]==value,:]
    p1 = featureX[featureX[:,10]==4,:]
    p0 = featureX[featureX[:,10]==2,:]
    p1=p1.shape[0];
    p0=p0.shape[0];
    if p0!=0:
        return np.log(p1/p0)
    else:
        return np.inf
        
        
        

In [78]:
x = logodds(3,1,data)
x

C:\Users\alloc\Anaconda3\envs\comp551a1\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in log
  # Remove the CWD from sys.path while we load stuff.


-inf

In [79]:
sigmoid(x)

0.0

In [80]:
sigmoid(-1)

0.2689414213699951

In [81]:
#update function
def update(weights,dataset,rate):
    new_weights=weights
    for element in dataset:
        new_weights=np.add(new_weights, rate*(element[1:10]*(element[10]-sigmoid(weights.dot(element[1:10])))))
    return new_weights
    
w = np.array([1,1,1,1,1,1,1,1,1], dtype=np.float64)
w.shape

(9,)

In [82]:
training_set = data[:500,:]
print(training_set[0])

[1.000025e+06 1.000000e+00 5.000000e+00 1.000000e+00 1.000000e+00
 1.000000e+00 2.000000e+00 1.000000e+00 3.000000e+00 1.000000e+00
 1.000000e+00 0.000000e+00]


In [83]:
test_set = data[499:,:]

In [84]:
#gradient descent is done here
w = np.array([0,0,0,0,0,0,0,0,0])
i=0
rate=0.001
while i<1000:
    w=update(w,training_set,rate)
    rate=rate/1.5
    i+=1
w

array([1.33  , 9.199 , 8.588 , 8.3775, 7.434 , 7.7855, 8.8395, 7.0175,
       7.9005])

In [85]:
#calculate accuracy of predictions
score = 0
for element in test_set:
    res=w.dot(element[1:10])
#     print(res>0,element[10])
    if(res>0.5 and element[10]==1) or (res<0.5 and element[10]==0):
        score+=1
        
print(score)
print(test_set[:,0].size)
print(score/184)

164
184
0.8913043478260869


In [97]:
class logisticReg:
    """class to build logistic regression model"""
        
    def __init__(self, dataset):
        self.dataset = dataset
        
    #update function
    def update(self,weights,dataset,rate):
        new_weights=weights
        for element in dataset:
            new_weights=np.add(new_weights, rate*(element[1:11]*(element[11]-sigmoid(weights.dot(element[1:11])))))
        return new_weights
    
        
    def fit(self,training_set):
        w = np.array([0,0,0,0,0,0,0,0,0,0])
        i=0
        rate=0.001
        while i<1000:
            w=self.update(w,training_set,rate)
            rate=rate/1.5
            i+=1
        return w
    
    
    def evaluate_acc(self , predictions):
        score = 0
        for pred in predictions:
            if pred[0]==pred[1]:
                score+=1
        
        print("Correct Predictions: ",score)
        print("Total Predictions: ",predictions[:,0].size)
        print("Accuracy Percentage: ",score/predictions[:,1].size*100,"%")
        
    def predict(self ,weights,data):
        res=data[:,1:11].dot(weights)
        return np.c_[ data, res>0.5 ]              
    
    def kfold(self,k,data):
        i=0
        batch_size=np.floor(data[:,1].size/k)
        while i < k -1 : 

            training_data=np.delete(data, np.s_[(int)(i*batch_size):(int)((i+1)*batch_size)], 0)
            test_data= data[(int)(i*(batch_size)):(int)((i+1)*(batch_size))]
            weights = self.fit(training_data)
            preds = self.predict(weights,test_data)
            print("\nSegmentation #",i+1," Results:")
            self.evaluate_acc(preds[:,11:13])
            i+=1
            
        training_data=np.delete(data, np.s_[(int)(i*batch_size):], 0)
        test_data= data[(int)(i*(batch_size)):]
        weights = self.fit(training_data)
        preds = self.predict(weights,test_data)
        print("\nSegmentation #",i+1," Results:")
        self.evaluate_acc(preds[:,11:13])
   

In [98]:
model = logisticReg(data)

In [99]:
weights = model.fit(training_set)

In [100]:
weights

array([-0.37047828, -0.26518061,  0.26075875,  0.23170381,  0.08756544,
       -0.25128753,  0.38175468, -0.25624658,  0.19570249, -0.10461199])

In [101]:
predictions = model.predict(weights,test_set)

In [102]:
predictions[:,10:12]

array([[ 2.,  1.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 2.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 2.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  1.],
       [ 1.,

In [103]:
model.evaluate_acc(predictions[:,10:12])

Correct Predictions:  27
Total Predictions:  184
Accuracy Percentage:  14.673913043478262 %


In [104]:
model.kfold(6,model.dataset)


Segmentation # 1  Results:
Correct Predictions:  84
Total Predictions:  113
Accuracy Percentage:  74.33628318584071 %

Segmentation # 2  Results:
Correct Predictions:  108
Total Predictions:  113
Accuracy Percentage:  95.57522123893806 %

Segmentation # 3  Results:
Correct Predictions:  94
Total Predictions:  113
Accuracy Percentage:  83.1858407079646 %

Segmentation # 4  Results:
Correct Predictions:  100
Total Predictions:  113
Accuracy Percentage:  88.49557522123894 %

Segmentation # 5  Results:
Correct Predictions:  107
Total Predictions:  113
Accuracy Percentage:  94.69026548672566 %

Segmentation # 6  Results:
Correct Predictions:  114
Total Predictions:  118
Accuracy Percentage:  96.61016949152543 %
