In [183]:
%config IPCompleter.greedy=True

In [184]:
import numpy as np

In [185]:
##load data

filename = 'breast-cancer-wisconsin.data'

data = np.loadtxt(filename, delimiter=',')
data


array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

In [186]:
#replaces the outcome in each vector
def replace(vector,index):
    if vector[index]==4:
        vector[index]=1
        return vector
    else:
        vector[index]=0
        return vector
    
# replace(data[0],10)

In [187]:
def preproc(dataset):
    for element in dataset:
        element=replace(element,10)
    return dataset    

preproc(data)
data[:,10]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1.

In [188]:
data.shape

(683, 11)

In [189]:
#sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

    

In [190]:
sigmoid(0.3)

0.574442516811659

In [191]:
#not actually needed

def logodds(index,value,dataset):
    featureX = dataset[dataset[:,index]==value,:]
    p1 = featureX[featureX[:,10]==4,:]
    p0 = featureX[featureX[:,10]==2,:]
    p1=p1.shape[0];
    p0=p0.shape[0];
    if p0!=0:
        return np.log(p1/p0)
    else:
        return np.inf
        
        
        

In [192]:
x = logodds(3,1,data)
x

inf

In [193]:
sigmoid(x)

1.0

In [194]:
sigmoid(-1)

0.2689414213699951

In [195]:
#update function
def update(weights,dataset,rate):
    new_weights=weights
    for element in dataset:
        new_weights=np.add(new_weights, rate*(element[1:10]*(element[10]-sigmoid(weights.dot(element[1:10])))))
    return new_weights
    
w = np.array([1,1,1,1,1,1,1,1,1], dtype=np.float64)
w.shape

(9,)

In [196]:
training_set = data[:500,:]

In [197]:
test_set = data[499:,:]

In [198]:
#gradient descent is done here
w = np.array([0,0,0,0,0,0,0,0,0])
i=0
rate=0.00001
while i<1000:
    w=update(w,training_set,rate)
    stepsize=stepsize/1.5
    i+=1
w

array([-0.21882073,  0.36064508,  0.25330695,  0.06686583, -0.36389154,
        0.37849836, -0.3940474 ,  0.21665365, -0.1177514 ])

In [199]:
#calculate accuracy of predictions
score = 0
for element in test_set:
    res=w.dot(element[1:10])
#     print(res>0,element[10])
    if(res>0 and element[10]==1) or (res<0 and element[10]==0):
        score+=1
        
print(score)
print(test_set[:,0].size)
print(score/184)

169
184
0.9184782608695652
