In [244]:
%config IPCompleter.greedy=True

In [245]:
import numpy as np

In [246]:
##load data

filename = 'breast-cancer-wisconsin.data'

data = np.loadtxt(filename, delimiter=',')
data


array([[1.000025e+06, 5.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 2.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 2.000000e+00],
       ...,
       [8.888200e+05, 5.000000e+00, 1.000000e+01, ..., 1.000000e+01,
        2.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 4.000000e+00],
       [8.974710e+05, 4.000000e+00, 8.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 4.000000e+00]])

In [247]:
#replaces the outcome in each vector
def replace(vector,index):
    if vector[index]==4:
        vector[index]=1
        return vector
    else:
        vector[index]=0
        return vector
    
# replace(data[0],10)

In [248]:
def preproc(dataset):
    for element in dataset:
        element=replace(element,10)
    return dataset    

preproc(data)
data[:,10]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1.

In [249]:
data.shape

(683, 11)

In [250]:
#sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

    

In [251]:
sigmoid(0.3)

0.574442516811659

In [252]:
#not actually needed

def logodds(index,value,dataset):
    featureX = dataset[dataset[:,index]==value,:]
    p1 = featureX[featureX[:,10]==4,:]
    p0 = featureX[featureX[:,10]==2,:]
    p1=p1.shape[0];
    p0=p0.shape[0];
    if p0!=0:
        return np.log(p1/p0)
    else:
        return np.inf
        
        
        

In [253]:
x = logodds(3,1,data)
x

inf

In [254]:
sigmoid(x)

1.0

In [255]:
sigmoid(-1)

0.2689414213699951

In [256]:
#update function
def update(weights,dataset,rate):
    new_weights=weights
    for element in dataset:
        new_weights=np.add(new_weights, rate*(element[1:10]*(element[10]-sigmoid(weights.dot(element[1:10])))))
    return new_weights
    
w = np.array([1,1,1,1,1,1,1,1,1], dtype=np.float64)
w.shape

(9,)

In [257]:
training_set = data[:500,:]

In [258]:
test_set = data[499:,:]

In [259]:
#gradient descent is done here
w = np.array([0,0,0,0,0,0,0,0,0])
i=0
rate=0.001
while i<1000:
    w=update(w,training_set,rate)
    rate=rate/1.5
    i+=1
w

array([-0.27440464,  0.25179458,  0.22146432,  0.07819044, -0.26061812,
        0.36595861, -0.26794322,  0.18610134, -0.10930147])

In [260]:
#calculate accuracy of predictions
score = 0
for element in test_set:
    res=w.dot(element[1:10])
#     print(res>0,element[10])
    if(res>0.5 and element[10]==1) or (res<0.5 and element[10]==0):
        score+=1
        
print(score)
print(test_set[:,0].size)
print(score/184)

174
184
0.9456521739130435


In [350]:
class logisticReg:
    """class to build logistic regression model"""
    x = 7
        
    def __init__(self, dataset):
        self.dataset = dataset
        
    #update function
    def update(weights,dataset,rate):
        new_weights=weights
        for element in dataset:
            new_weights=np.add(new_weights, rate*(element[1:10]*(element[10]-sigmoid(weights.dot(element[1:10])))))
        return new_weights
    
        w = np.array([1,1,1,1,1,1,1,1,1], dtype=np.float64)
        w.shape   
        
    def fit(self,training_set):
        w = np.array([0,0,0,0,0,0,0,0,0])
        i=0
        rate=0.001
        while i<1000:
            w=update(w,training_set,rate)
            rate=rate/1.5
            i+=1
        return w
    
    
    def evaluate_acc(self , predictions):
        score = 0
        for pred in predictions:
            if pred[0]==pred[1]:
                score+=1
        
        print("Correct Predictions: ",score)
        print("Total Predictions: ",predictions[:,0].size)
        print("Accuracy Percentage: ",score/predictions[:,1].size*100,"%")
        
    def predict(self ,weights,data):
        res=data[:,1:10].dot(weights)
        return np.c_[ data, res>0.5 ]              
    
    def kfold(self,k):
        i=0
        batch_size=np.floor(self.dataset[:,1].size/k)
        while i < k -1 : 

            training_data=np.delete(self.dataset, np.s_[(int)(i*batch_size):(int)((i+1)*batch_size)], 0)
            test_data= self.dataset[(int)(i*(batch_size)):(int)((i+1)*(batch_size))]
            weights = self.fit(training_data)
            preds = self.predict(weights,test_data)
            print("\nSegmentation #",i+1," Results:")
            self.evaluate_acc(preds[:,10:12])
            i+=1
            
        training_data=np.delete(self.dataset, np.s_[(int)(i*batch_size):], 0)
        test_data= self.dataset[(int)(i*(batch_size)):]
        weights = self.fit(training_data)
        preds = self.predict(weights,test_data)
        print("\nSegmentation #",i+1," Results:")
        self.evaluate_acc(preds[:,10:12])
   

In [351]:
model = logisticReg(data)

In [352]:
weights = model.fit(training_set)

In [353]:
weights

array([-0.27440464,  0.25179458,  0.22146432,  0.07819044, -0.26061812,
        0.36595861, -0.26794322,  0.18610134, -0.10930147])

In [354]:
predictions = model.predict(weights,test_set)

In [355]:
predictions[:,10:12]

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.

In [356]:
model.evaluate_acc(predictions[:,10:12])

Correct Predictions:  174
Total Predictions:  184
Accuracy Percentage:  94.56521739130434 %


In [357]:
model.kfold(6)


Segmentation # 1  Results:
Correct Predictions:  83
Total Predictions:  113
Accuracy Percentage:  73.45132743362832 %

Segmentation # 2  Results:
Correct Predictions:  106
Total Predictions:  113
Accuracy Percentage:  93.80530973451327 %

Segmentation # 3  Results:
Correct Predictions:  93
Total Predictions:  113
Accuracy Percentage:  82.30088495575221 %

Segmentation # 4  Results:
Correct Predictions:  93
Total Predictions:  113
Accuracy Percentage:  82.30088495575221 %

Segmentation # 5  Results:
Correct Predictions:  107
Total Predictions:  113
Accuracy Percentage:  94.69026548672566 %

Segmentation # 6  Results:
Correct Predictions:  113
Total Predictions:  118
Accuracy Percentage:  95.76271186440678 %
